### ISSUE TITLE
Support for Lambda layers

### ISSUE THREAD

**Issue by niclaswue** [Dobiasd/frugally-deep#54] opened 2018-05-29 23:11 UTC
Hi Tobias,

first of all frugally-deep is really awesome. Thanks for creating it! A friend of yours actually pointed me at this and it saved me and my team a lot of work already :)

At the moment I am trying to predict a steering angle to steer an autonomous car and implemented the Nvidia model described in their paper. However it normalizes the pixels of the camera image in a Lambda layer, which doesn't seem to be implemented yet.

I get the following error at runtime:
`terminate called after throwing an instance of 'std::runtime_error'
  what():  unknown layer type: Lambda
`

Do you have any plans on implementing Lambda layers?

**Comment by Dobiasd** [comment] 2018-05-30 06:26
Hi, and thanks for the positive feedback. :)

I did not yet plan to implement lambdas, but perhaps it will turn out to actually be not that hard.

Let's see. For example you have the following code in Python

```python
def my_func(input_tensor):
    # output_tensor = ... some code ...
    return output_tensor

model.add(Lambda(my_func))
```

Now it would be nice if we could
- serialize the lamba function itself
- load it with the model again in C++
- convert the functions code to C++ and compile/interpret it at runtime

But this (the last step) sounds extremely complicated to me.

So in Python you would provide your lambda as a custom object when loading the model again:

```python
model = load_model('model.h5', custom_objects={'my_func': my_func})
```

If you now would re-implement your function in C++, perhaps we could have an interface like so:

```cpp
fdeep::tensor3s my_func(const fdeep::tensor3s& input)
{
    // fdeep::tensor3s output = ... some code ...
    return output;
}

using custom_function_t = std::function<fdeep::tensor3s(const fdeep::tensor3s&)>;

const std::unordered_map<std::string, custom_function_t> custom_functions = {
    {"my_func", my_func}
};

fdeep::load_model("model.json", custom_functions);
```

What do you think about this?

**Comment by PhilippKopp** [comment] 2018-06-01 11:31
Hi! We came across this today too. In our case we have an activation layer defined as lambda function. 
Your idea is really great and would help us a lot! It shouldn't be a problem for users to define the layer in C++ too as lambda.

**Comment by Dobiasd** [comment] 2018-06-01 11:44
Does your activation layer only map over the values of the tensor one by one like `relu` or `sigmoid`, or does it do some kind of accumulation/reduction step like `softmax`?

In the first case, an easier (and a more specific) function type like
```cpp
float_type my_func(float_type value)
```
would already suffice.

**Comment by PhilippKopp** [comment] 2018-06-01 14:06
Thanks for the quick reply @Dobiasd !
No it's actually 'softmax' that doesn't normalize on the standard axis. Although keras supports that in https://github.com/keras-team/keras/blob/master/keras/activations.py#L14 if I want to specify the non 1 axis and use this in an activation layer, I have to use a lambda function. At least I haven't found a different way. If you a have a solution without lambda function It would help aswell :)

I don't know @niclaswue , so we have different use cases here.

**Comment by Dobiasd** [comment] 2018-06-01 14:46
@PhilippKopp Just to make sure, I understand correctly. Did you already explore
```python
model.add(Dense(1000))
model.add(Activation('softmax', axis=2))
```
instead of
```python
model.add(Dense(1000, activation='softmax'))
```
?

**Comment by Dobiasd** [comment] 2018-06-02 06:56
@PhilippKopp Just to make sure, I understand correctly:

I guess you have three options to add a softmax layer.

1)
```python
Conv2D(32, (3, 3), activation='softmax') # or something other than Conv2D
```

2)
```python
Activation('softmax')
```

3)
```python
Softmax(axis=2)
```

Did you already explore option 3?

**Comment by linhqhta** [comment] 2018-06-04 02:12
Hi Dobiasd,
Thank you for your awesome work!

I have a problem when convert mymodel.h5 to mymodel.json when using **python3 convert_model.py**

Traceback (most recent call last):
  File "convert_model.py", line 507, in <module>
    main()
  File "convert_model.py", line 503, in main
    convert(in_path, out_path)
  File "convert_model.py", line 450, in convert
    model = load_model(in_path, custom_objects={'relu6': relu6})
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 274, in load_model
    sample_weight_mode=sample_weight_mode)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 626, in compile
    loss_functions.append(losses.get(loss.get(name)))
  File "/usr/local/lib/python3.5/dist-packages/keras/losses.py", line 122, in get
    return deserialize(identifier)
  File "/usr/local/lib/python3.5/dist-packages/keras/losses.py", line 114, in deserialize
    printable_module_name='loss function')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 164, in deserialize_keras_object
    ':' + function_name)
ValueError: Unknown loss function:<lambda>

Have you any suggestion to solve this?
Thank you very much!

**Comment by Dobiasd** [comment] 2018-06-04 05:37
@linhqhta Thanks for the positive feedback. It seems like your problem has nothing to do with lambda layers. For further questions please open a separate issue.

The errors message you show seems to be Keras related. Please update to the latest version (Keras and TensorFlow) and try again. Also please make sure you do not export your model with any custom loss function from your code. If you are using a custom loss, try recompiling the model `model.compile(loss='mse', optimizer='sgd')` (just something default) before calling `model.save(...)` in your code.

Once you are able to read your `.h5` file with `load_model` in some test code you write, you should be able to use `convert_model.py`.

**Comment by linhqhta** [comment] 2018-06-04 06:31
@Dobiasd : Thank you for your quick reply!
I'll try on as you suggestion

**Comment by linhqhta** [comment] 2018-06-04 09:15
@Dobiasd 
My source code to save model:
#============
loss_out = Lambda(ctc_lambda_func, output_shape=(1,), name='ctc')([y_pred, labels, input_length, label_length])
model = Model(inputs=[input_data, labels, input_length, label_length], outputs=loss_out)
model.compile(loss={'ctc': lambda y_true, y_pred: y_pred}, optimizer=sgd)
model.fit_generator(generator=tiger_train.next_batch(), 
                            steps_per_epoch=tiger_train.n,
                            epochs=epochs, 
                            validation_data=tiger_val.next_batch(), 
                            validation_steps=tiger_val.n)
model.save('./mymodel.h5')
#============

After the model saved, i loaded mymodel.h5 successfully by python code.
When i convert mymodel.h5 to mymodel.json by using python3 convert_model.py, the folowing errors are showed:
Traceback (most recent call last):
  File "keras_to_tensorflow.py", line 123, in <module>
    raise err
  File "keras_to_tensorflow.py", line 114, in <module>
    net_model = load_model(weight_file_path)
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 274, in load_model
    sample_weight_mode=sample_weight_mode)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 626, in compile
    loss_functions.append(losses.get(loss.get(name)))
  File "/usr/local/lib/python3.5/dist-packages/keras/losses.py", line 122, in get
    return deserialize(identifier)
  File "/usr/local/lib/python3.5/dist-packages/keras/losses.py", line 114, in deserialize
    printable_module_name='loss function')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 164, in deserialize_keras_object
    ':' + function_name)
ValueError: **Unknown loss function:<lambda>**

Have you any suggestion to me?

**Comment by Dobiasd** [comment] 2018-06-04 10:19
@linhqhta: As already suggested above, for using `frugally-deep/keras_export/convert_model.py` please save the model without a custom loss function. You only need it for training, not for prediction. So there is no need for frugally-deep to support it.

Concretely in your code this means adding the following two lines to the end after `model.save('./mymodel_with_custom_optimizer.h5')`:
```python3
model.compile(loss='mse', optimizer='sgd') # replace custom loss function with a default one
model.save('./mymodel_without_custom_optimizer.h5') # save without custom optimizer
```

Then use
```bash
python3 frugally-deep/keras_export/convert_model.py mymodel_without_custom_optimizer.h5 mymodel.json
```

**Comment by PhilippKopp** [comment] 2018-06-05 12:42
Hey @Dobiasd 
I investigated this softmax problem a bit further and I think I don't need a lambda function here. The original model I am using was pure tensorflow without keras. In tensorflow different axis were specified, but I realised that keras always performes softmax on the last axis (-1), when adding softmax with option 1 or 2. Which is actually also the case in my network. 

Just for future reference I tried option 3. There I get the following error when using it as last layer: 
TypeError: Output tensors to a Model must be Keras tensors. Found: Tensor("Softmax:0", shape=(?, 3), dtype=float32)
So I guess if someone needs to perform the softmax on the not last axis, you would still have to use a lambda function.

Thanks a lot for you help! Really great support.

**Comment by Dobiasd** [comment] 2018-06-05 14:45
I'm glad your problem is solved, even if it was by recognizing you actually don't need this feature. ;)

Just out of interest I tried out three different versions to add a softmax layer with `axis != -1`, and all three run without any error.

```python
from keras.models import Sequential
from keras.layers import Activation, Softmax

model = Sequential([
    Activation('relu', input_shape=(6,7,8)),
    Softmax(axis=1)
])
model.compile(optimizer='nadam', loss='categorical_crossentropy')
```

```python
from keras.models import Sequential
from keras.layers import Activation, Softmax

model = Sequential()
model.add(Activation('relu', input_shape=(6,7,8)))
model.add(Softmax(axis=1))
model.compile(optimizer='nadam', loss='categorical_crossentropy')
```

```python
from keras.models import Model
from keras.layers import Input, Softmax, Dense

inp = Input(shape=(6,7,8))
x = Softmax(axis=1)(inp)
model = Model(inputs=inp, outputs=x)
model.compile(optimizer='nadam', loss='categorical_crossentropy')
```

Do I have to do something else to reproduce your error?

---

The thing to keep in mind however is that frugally-deep currently would not support to convert such a model, since softmax is only supported as activation (i.e. `Dense(..., activation='softmax')` and `Activation('softmax')`) but not as an actual `Softmax` layer. But up to now it seems as if nobody is using softmax with `axis != -1`. I guess everybody just uses it as the activation behind the last dense layer. And with such a one-dimensional output the axis is clear anyway. :)

**Comment by Dobiasd** [comment] 2018-06-05 14:55
@niclaswue: Is this issue still of interest to you?

If yes, I'd love to get to know:

1) Does your activation layer only map over the values of the tensor one by one like relu or sigmoid, or does it do some kind of accumulation/reduction step like softmax?
2) What do you think about [the proposed interface for using lambda layers](https://github.com/Dobiasd/frugally-deep/issues/54#issuecomment-393044777)?

**Comment by PhilippKopp** [comment] 2018-06-05 20:08
Aah there is also a Softmax layer and not just a softmax activation function. Just realizing that the layer is with a capital 'S'. I had tried:
```python
from keras.layers import Input, Dense
from keras.models import Model
from keras.activations import softmax

inputs = Input(shape=(4,))
x = Dense(5, activation='relu')(inputs)
x = Dense(3)(x)
predictions = softmax(x, axis=2)
model = Model(inputs=inputs, outputs=predictions)
```
Didn't know that! Thanks for the clarification.

**Comment by Dobiasd** [comment] 2018-06-13 12:30
@niclaswue: Since you [did not yet reply](https://github.com/Dobiasd/frugally-deep/issues/54#issuecomment-394740744) I assume this issue is no longer of interest to you. Thus I'll close it for now.

Feel free to re-open it in case you would like to continue with it. :)

**Closed by Dobiasd** 2018-06-13 12:30 UTC
