### ISSUE TITLE
Building the unit tests(doctest.h) error

### ISSUE THREAD

**Issue by likejazz** [Dobiasd/frugally-deep#28] opened 2018-03-13 03:23 UTC
I've done the following commands as described in README.

```
# install doctest
wget https://raw.githubusercontent.com/onqtam/doctest/master/doctest/doctest.h
sudo mv ./doctest.h /usr/local/include/doctest.h

# build unit tests
cmake -DFDEEP_BUILD_UNITTEST=ON ..
```

But an error occurred that did not find `hunter_add_package(doctest)`.

```
$ cmake -DFDEEP_BUILD_UNITTEST=ON ..
-- ===( frugally-deep 0.2.3 )===
-- Building Unit Tests
CMake Error at test/CMakeLists.txt:52 (find_package):
  Could not find a package configuration file provided by "doctest" with any
  of the following names:

    doctestConfig.cmake
    doctest-config.cmake

  Add the installation prefix of "doctest" to CMAKE_PREFIX_PATH or set
  "doctest_DIR" to a directory containing one of the above files.  If
  "doctest" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/Users/kaonpark/workspace/github.com/Dobiasd/frugally-deep/build/CMakeFiles/CMakeOutput.log".
```

I'd like to perform unit tests. can I get help?

Thanks.

**Comment by headupinclouds** [comment] 2018-03-13 04:57
Hunter is disabled by default, so the `hunter_add_package(doctest)` call is a noop.

See:

https://github.com/Dobiasd/frugally-deep/blob/562349afe9c98cc6336120873738764d2bfa0c12/cmake/hunter.cmake#L1

```
option(HUNTER_ENABLED "Enable Hunter package manager support" OFF)
```

You can enable hunter by defining `HUNTER_ENABLED=ON` in your CMake options, and it will be managed for you.

**Comment by likejazz** [comment] 2018-03-13 06:04
Great, It works now!
I hope this guide would be added to README.
Thanks.

**Comment by Dobiasd** [comment] 2018-03-13 06:14
@headupinclouds `hunter_add_package(doctest)` is line `51`. The error reported is in line 52 (`find_package`). I have the same problem on my machine. I think it should still be possible to build the unittest without hunter having anything to do with it. Is this a problem since [PR#14](https://github.com/Dobiasd/frugally-deep/pull/14)?

**Comment by headupinclouds** [comment] 2018-03-13 12:07
I think the issue is that `doctest` needs to be installed here so that the `find_package()` call will work.

```
wget https://raw.githubusercontent.com/onqtam/doctest/master/doctest/doctest.h
sudo mv ./doctest.h /usr/local/include/doctest.h
cmake -DFDEEP_BUILD_UNITTEST=ON ..
```

That was changed in this part of https://github.com/Dobiasd/frugally-deep/pull/14

```
* update unit tests to use doctest::doctest as explicit CONFIG mode dependency: (same pkgconfig stuff used here
```

So this should just require an explicit installation step to work.  That installation step is part of the doctest CMakeLists.txt.  I see this doesn't match the README.  Shall I send a PR?  I can also send some notes about the frugally-deep Hunter package:

https://docs.hunter.sh/en/latest/packages/pkg/frugally-deep.html?highlight=frugally

Side note: Wherever I said "pkgconfig" previously, it should be replaced with the (related but different) "CMake config install".

**Comment by headupinclouds** [comment] 2018-03-13 12:15
I've sent a PR with an update to the README https://github.com/Dobiasd/frugally-deep/pull/29

**Comment by headupinclouds** [comment] 2018-03-13 12:52
> I can also send some notes about the frugally-deep Hunter package:

I've sent a PR with Hunter "quick start" notes: https://github.com/Dobiasd/frugally-deep/pull/30

**Comment by Dobiasd** [comment] 2018-03-14 12:14
@headupinclouds Thank a lot. But before merging I would like to better understand the issue, and I hope you can help me with that. =)

Building the unit tests for [FunctionalPlus](https://github.com/Dobiasd/FunctionalPlus) is still working with the following approach:
```bash
git clone https://github.com/Dobiasd/FunctionalPlus
cd FunctionalPlus
mkdir build
cd build
wget https://raw.githubusercontent.com/onqtam/doctest/master/doctest/doctest.h
sudo mv ./doctest.h /usr/local/include/doctest.h
cmake -DFPLUS_BUILD_UNITTEST=ON ..
# ...
-- Build files have been written to: /home/tobias/Desktop/FunctionalPlus/build/FunctionalPlus/build

```

Why does the same method have to fail for frugally-deep?
```bash
git clone https://github.com/Dobiasd/frugally-deep
cd frugally-deep
mkdir build
cd build
wget https://raw.githubusercontent.com/onqtam/doctest/master/doctest/doctest.h
sudo mv ./doctest.h /usr/local/include/doctest.h
cmake -DFDEEP_BUILD_UNITTEST=ON ..
# ...
-- Configuring incomplete, errors occurred!
```

**Comment by Dobiasd** [comment] 2018-03-14 20:36
Thanks a lot for the explanation. I think I don't prefer one version over the other. However I would like it to be consistent regarding fplus and fdeep. Could you adjust one or the other to whatever version you think is better/cleaner?

**Comment by headupinclouds** [comment] 2018-03-15 01:26
Sure.  I'll update fplus to use the installed `doctest`.

**Comment by Dobiasd** [comment] 2018-03-15 14:17
Sorry, but I've got one more question. On Travis CI the approach with [`wget` and `cp` for doctest](https://github.com/Dobiasd/frugally-deep/blob/master/.travis.yml#L20-L21) seems to work. Do you know why?

**Comment by headupinclouds** [comment] 2018-03-15 14:51
Because of this :)

https://github.com/Dobiasd/frugally-deep/blob/49bf4c3e45e1256dd0eb7f3340b25d9a66aaa0f2/.travis.yml#L55-L60

The `cp` step should probably be removed.

**Comment by Dobiasd** [comment] 2018-03-15 15:17
Oh, of course, sorry. Thanks for the clarification. I [cleaned it up](https://github.com/Dobiasd/frugally-deep/commit/2d9a4841abdd0251062325a1d95ed7e04b79b3d9).

**Comment by Dobiasd** [comment] 2018-03-22 13:18
@headupinclouds Did you already have time to look into the fplus change (use installed `doctest`)?

**Comment by Dobiasd** [comment] 2018-03-22 13:19
@likejazz Is this issue here solved from your point of view?

**Comment by headupinclouds** [comment] 2018-03-22 14:42
Here it is: https://github.com/Dobiasd/FunctionalPlus/pull/122

**Comment by Dobiasd** [comment] 2018-03-22 20:48
Thanks a lot. :+1:

**Comment by Dobiasd** [comment] 2018-03-28 08:57
@likejazz: I consider this as fixed and close the issue now. If you still encounter any problems, feel free to re-open it.

**Closed by Dobiasd** 2018-03-28 08:57 UTC
