### ISSUE TITLE
Error: "Unable to load: fdeep_model.json"

### ISSUE THREAD

**Issue by LeviVu** [Dobiasd/frugally-deep#106] opened 2018-12-11 16:08 UTC
Dear Tobias

Thanks for uploading all of your hard work! 

I am trying to implement my LSTM neural network (that I trained with Keras in Python 3.6) in a C++ application. Converting your example model (create_model.py) as well as my own LSTM model into JSON format works properly I think. However when I try to use these JSON files in Visual Studio 2015 using your example CPP file, I ran into errors.  After succesfully building the project, I receive following error:

Unhandled exception at 0x750A1812 in Project1.exe: Microsoft C++ exception: std::runtime_error at memory location 0x0133F910.

"Unable to load: fdeep_model.json"

By looking a bit closer, the initial construction of a fdeep::model object gives problems.
I think there are two possible ways it goes wrong, or it doesn't find/is able to read the JSON file or something's wrong inside the code itself (different versions etc)?

------------------------------------------------------------------------------------------------------------

Currently I run following main cpp program:

// main.cpp
#define FDEEP_FLOAT_TYPE double
#include <fdeep/fdeep.hpp>

int main()
{
	const auto model = fdeep::load_model("fdeep_model.json");
}

-------------------------------------------------------------------------------------------------------------------

I am using all the header files in C++ described in your description. As for python, I am using the newest versions of tensorflow and keras packages.

[JSON.zip](https://github.com/Dobiasd/frugally-deep/files/2668461/JSON.zip)

**Comment by Dobiasd** [comment] 2018-12-11 16:32
> * If you have a model and you get unexpected errors when converting it for or when using it with frugally-deep, please upload and post a link to your model file (`.h5`). Make sure to first check if an update of TensorFlow and Keras to the latest versions already fixed the issue.
> * In case the problem can be reproduced with just code, please create a [SSCCE](http://sscce.org/) from it.
> * If you are missing a feature (e.g. layer type) in frugally-deep and want to request its implementation, please let us know your use case as motivation. ;-)
> * Feel free to also submit any other feedback, suggestions or questions you might have.

Yes, this is the content of [`ISSUE_TEMPLATE.md`](https://github.com/Dobiasd/frugally-deep/blob/master/.github/ISSUE_TEMPLATE.md). How can I help you? :slightly_smiling_face:

**Comment by LeviVu** [comment] 2018-12-12 08:03
> > * If you have a model and you get unexpected errors when converting it for or when using it with frugally-deep, please upload and post a link to your model file (`.h5`). Make sure to first check if an update of TensorFlow and Keras to the latest versions already fixed the issue.
> > * In case the problem can be reproduced with just code, please create a [SSCCE](http://sscce.org/) from it.
> > * If you are missing a feature (e.g. layer type) in frugally-deep and want to request its implementation, please let us know your use case as motivation. ;-)
> > * Feel free to also submit any other feedback, suggestions or questions you might have.
> 
> Yes, this is the content of [`ISSUE_TEMPLATE.md`](https://github.com/Dobiasd/frugally-deep/blob/master/.github/ISSUE_TEMPLATE.md). How can I help you? 🙂

Yeah sorry, was already committed before writing down the issue. :)

**Comment by LeviVu** [comment] 2018-12-12 11:18
Thanks for the fast reply! 👍  The parsing and construction of my LSTM network now works fine! 💯 However I am struggling how to define the input in the LSTM Network in C++.

In my python scripts, I am using a 3D Tensor: (batch_size, timesteps, input_dim), so I guess I should use the tensor3.hpp but looking at the headers of the lstm layers, I notice:

recurrent_ops.hpp(140, 32): lstm_result = {tensor5(shape5(1, 1, 1, n_timesteps, n_units), float_type(0))};

Below you can find a short python code how I run my predictions in Python. I am using 10 timestamps, each timestamp containing 3 features.

data = np.array([[0.1, 0.2, 0.3],[0.1, 0.2, 0.3],[0.1, 0.2, 0.3],[0.1, 0.2, 0.3],[0.1, 0.2, 0.3],[0.1, 0.2, 0.3],[0.1, 0.2, 0.3],[0.1, 0.2, 0.3],[0.1, 0.2, 0.3],[0.1, 0.2, 0.3]])
data = data.reshape((1, 10, 3))
predictions = Model.predict(data)

Thanks in advance!

**Comment by Dobiasd** [comment] 2018-12-12 12:58
Can you post a [minimal but complete example](https://stackoverflow.com/help/mcve) of how to reproduce your issue?

Ideally with a minimal python code and minimal C++ code. Here is an example of the style I'm thinking of: https://gist.github.com/Dobiasd/14a3e233725a16bb7c86ca6f4d81a825

Without knowing what exactly you are doing, everything is just guesswork.

**Comment by Dobiasd** [comment] 2018-12-12 13:06
OK, but since you uploaded a `JSON.zip` I had a look into it.
It includes two files:
- `fdeep_model.json`
- `fdeep.json`

From their content, I guess that `fdeep_model.json` is irrelevant to your question, and that `fdeep.json` is the model you are concerned about.

So here is a minimal C++ example, loading this model and doing a forward pass on it:

```cpp
#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("fdeep.json");
    const fdeep::tensor5 input(fdeep::shape5(1, 1, 1, 10, 3), 0.0f);
    const auto output = model.predict({input});
    std::cout << fdeep::show_tensor5s(output) << std::endl;
}
```

Output:
```
Loading json ... done. elapsed time: 0.062972 s
Running test 1 of 1 ... done. elapsed time: 0.000968 s
Loading, constructing, testing of fdeep.json took 0.071614 s overall.
[[[[0.0002]]]]
```

If this does not help, please help me to understand the issue with actual code.

**Comment by LeviVu** [comment] 2018-12-12 14:11
Thanks! This piece of code helps me indeed to perform a forward pass on the model. 🥇 

To help you understand the issue: I constructed an LSTM network which uses its 10 previous timestamps, (each timestamp contains 3 features) to predict the output at the next timestamp, this is a single value output. Thus batch size: 1, previous time stamps: 10 and features: 3. 

If I run your given C++ example (indeed with fdeep.json), doing a forward pass and compare this result with a prediction in Python, I get the same prediction. 👍 In this python code I stated that each feature for each timestamp equals zero.  Cause now I guess all features are valued as 0 in the C++ code, as stated by '0.0f'

data = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]] data = data.reshape((1, 10, 3))
predictions = Model.predict(data)

Now is my last question: how to assign the values of these three features for those 10 previous timestamps in C++?

For example in python, data as:
data = np.array([[21, 1, 10], [22, 2, 9], [20, 1, 9], [19, 4, 15], [12, 3, 9], [21, 1, 10], [22, 2, 9], [2, 1, 9], [14, 4, 15], [12, 3, 6]])

Thanks for all your help! Helps me a lot!

**Comment by Dobiasd** [comment] 2018-12-12 14:54
I was hoping the examples, which the `README` links to, should cover this. Especially this one: https://gist.github.com/Dobiasd/8f41ef8bf4198ab535060a78b53f2008

But here is the same, but this time hand-tailored to your model:

```cpp
#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("fdeep.json");
    fdeep::tensor5 input(fdeep::shape5(1, 1, 1, 10, 3), 0.0f);
    input.set(0, 0, 0, 0, 0, 12.34);
    input.set(0, 0, 0, 0, 1, 23.45);
    input.set(0, 0, 0, 0, 2, 34.56);
    input.set(0, 0, 0, 1, 0, 45.67);
    // ...
    input.set(0, 0, 0, 9, 1, 56.78);
    input.set(0, 0, 0, 9, 2, 67.89);
    const auto output = model.predict({input});
    std::cout << fdeep::show_tensor5s(output) << std::endl;
}
```

Or, if you already have your values in an `std::vector`:

```cpp
#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("fdeep.json");
    const std::vector<float> v = {1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3};
    const fdeep::shared_float_vec sv(fplus::make_shared_ref<fdeep::float_vec>(v));
    fdeep::tensor5 input(fdeep::shape5(1, 1, 1, 10, 3), sv);
    const auto output = model.predict({input});
    std::cout << fdeep::show_tensor5s(output) << std::endl;
}
```

**Comment by Dobiasd** [comment] 2018-12-20 07:46
@LeviVu Are your problems solved? If so, feel free to close this issue. :)

**Comment by LeviVu** [comment] 2018-12-20 10:22
Dear 

My problems are completely solved now! Big thank you! 👍 

Kind regards
Levi

**Closed** 2018-12-20 10:22 UTC
