### ISSUE TITLE
ValueError: Refusing to perform an overparameterized separable convolution

### ISSUE THREAD

**Issue by MyraBaba** [Dobiasd/frugally-deep#42] opened 2018-05-10 14:09 UTC
Hi,

I try to use your awesome solution. few questions:

I have below error when I ran : 

> ValueError: Refusing to perform an overparameterized separable convolution: channel_multiplier * in_channels = 1 * 2 = 2 > 1 = out_channels

my training code:
`from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras import backend as K
from model import create_model
from math import ceil

model = create_model()
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

`

is this output usable from your code or need to change ie:optimizer or not supported . ?

Best

**Comment by Dobiasd** [comment] 2018-05-10 20:45
Hi,

the optimizer does not matter, because it is only used during training, not for prediction.

Can you please post the minimal (but complete) code needed to reproduce your problem? ([ref1](https://stackoverflow.com/help/mcve), [ref2](http://sscce.org/))

**Comment by MyraBaba** [comment] 2018-05-10 20:59
Below is the code that I produced the weights.h5 . and want to use from c++

I hope it will help.

Thanks for your time.


```

import argparse

a = argparse.ArgumentParser(description="Train a simple CNN model and save improved weights.")
a.add_argument("--bsize", help="provide batch size for training (default: 40)", type=int, default=40)
args = a.parse_args()

from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras import backend as K
from model import create_model
from math import ceil

model = create_model()
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

# Prepare the data

# using flow_from_directory(), generate batches of image data (and their labels)
batch_size = args.bsize

train_datagen = ImageDataGenerator(
            rotation_range=10, # range (0-180) within which to randomly rotate pictures
            # width_shift_range=0.2, # as fraction of width, range within to which randomly translate pictures
            # height_shift_range=0.2, # same as above, but with height
            rescale=1./255, # RBG coefficient values 0-255 are too hight to process. instead, represent them as values 0-1
            # shear_range=0.2, # random shearing transformations
            zoom_range=0.1, # randomly zooming inside pictures
            horizontal_flip=False,
            fill_mode='nearest') # strategy for filling in newly created pixels, which can appear after a rotation or a width/height shift

val_datagen = ImageDataGenerator(
            rotation_range=10, # range (0-180) within which to randomly rotate pictures
            # width_shift_range=0.2, # as fraction of width, range within to which randomly translate pictures
            # height_shift_range=0.2, # same as above, but with height
            rescale=1./255, # RBG coefficient values 0-255 are too hight to process. instead, represent them as values 0-1
            # shear_range=0.2, # random shearing transformations
            zoom_range=0.1, # randomly zooming inside pictures
            horizontal_flip=False,
            fill_mode='nearest') # strategy for filling in newly created pixels, which can appear after a rotation or a width/height shift


# generate batches of augmented image data, given the path of the original images

# instantiate generators of augmented image batches (and their labels) via .flow(data, labels) or .flow_from_directory(directory)
# this generator will read pictures found in subfolders and indefinitely generate batches of augmented image data
train_generator = train_datagen.flow_from_directory(
        '../../../dataset/split_data/train/',  # this is the target directory
        target_size=(150, 150),  # all images will be resized to 150x150
        batch_size=batch_size,
        class_mode='categorical')  # since we use binary_crossentropy loss, we need binary labels

# this is a similar generator, for validation data
val_generator = val_datagen.flow_from_directory(
        '../../../dataset/split_data/validation/',
        target_size=(150, 150),
        batch_size=batch_size,
        class_mode='categorical')



filepath="weights.h5"

checkpoint_callback = ModelCheckpoint(
                        filepath,
                        monitor='val_acc',
                        verbose=1,
                        save_best_only=True,
                        mode='max')

early_stop_callback = EarlyStopping(
                monitor='val_acc',
                # verbose=0, # decides what to print
                # min_delta=0, # threshold to whether quantify a loss at some epoch as improvement or not. If the difference of loss is below min_delta, it is quantified as no improvement
                # mode='auto', # depends on the direction of the monitored quantity (is it supposed to be decreasing or increasing), since we monitor the loss, we can use min.        
                patience=3,
                mode='max') 

callbacks_list = [checkpoint_callback, early_stop_callback]

history = model.fit_generator(
            train_generator,
            steps_per_epoch=(ceil(len(train_generator.filenames) // batch_size)),
            epochs=50,
            validation_data=val_generator,
            validation_steps=(ceil(len(val_generator.filenames) // batch_size)),
            callbacks=callbacks_list)




```

**Comment by Dobiasd** [comment] 2018-05-10 21:06
```bash
$ python3 github_guy.py 
...
Traceback (most recent call last):
  File "fdeep_issue_42.py", line 13, in <module>
    from model import create_model
ModuleNotFoundError: No module named 'model'
```

**Comment by MyraBaba** [comment] 2018-05-10 21:14
model.py

`from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense

def create_model():
    model = Sequential()
    model.add(Conv2D(32, (3, 3), input_shape=(150, 150, 3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    model.add(Conv2D(32, (3, 3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    model.add(Conv2D(64, (3, 3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    # so far, the model outputs 3D feature maps (height, width, features)

    # then, add two fully connected layers
    model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors
    model.add(Dense(64))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))

    # end the model with 10 units and a sigmoid activation
    model.add(Dense(10))
    model.add(Activation('sigmoid'))

    return model`

**Comment by MyraBaba** [comment] 2018-05-10 21:29
here : https://drive.google.com/open?id=1GPOAjRoqfcm46h_0-Vxf4CO_UYhZGeAH

**Comment by MyraBaba** [comment] 2018-05-10 23:09
https://github.com/lrojas12/distracted-driver-detection

full project..
distracted-driver-detection/src/keras/base/train.py is our code.

**Comment by Dobiasd** [comment] 2018-05-11 05:06
In your repo I [find](https://github.com/lrojas12/distracted-driver-detection/search?utf8=✓&q="model.save"&type=) three `model.save_weights()` calls and no `model.save()` call. Do you export the `h5` file you try to convert for frugally-deep with `model.save_weights()` or `model.save()`?

**Comment by Dobiasd** [comment] 2018-05-11 08:20
So, I tried out to convert your `weights.h5` using `convert_model.py` and it worked fine:

```
$ python3 convert_model.py ~/Downloads/weights.h5 fdeep_issue_42.json
Using TensorFlow backend.
loading /home/tobias/Downloads/weights.h5
Forward pass took 0.748781 s.
Forward pass took 0.00134 s.
Forward pass took 0.001701 s.
Starting performance measurements.
Forward pass took 0.001519 s.
Forward pass took 0.00148 s.
Forward pass took 0.001141 s.
Forward pass took 0.001198 s.
Forward pass took 0.001941 s.
Forward pass took 0.0014558 s on average.
writing fdeep_issue_42.json
```

It seems like you not only saved the weights but the whole model, which is correct.

Also I can load your converted model using frugally-deep in C++:

```cpp
const auto model = fdeep::load_model("fdeep_issue_42.json", true);
```

```
Parsing json ... done. elapsed time: 0.099336 s
Running test 1 of 1 ... done. elapsed time: 0.012192 s
```

So I can not reproduce your problem. You model works fine on my machine (tm). Please update Keras, TensorFlow and frugally-deep to the latest versions on your machine and try again.

I'll close this issue for now. If the problem still exists, please re-open this issue and post the exact steps you are using when you encounter the problem.

**Comment by MyraBaba** [comment] 2018-05-11 08:37
can you tell me the your environment ? tensorflow , keras and python version ?

**Comment by MyraBaba** [comment] 2018-05-11 08:45
After upgrading the latest tensorflow and keras all is good.  successfully exported. 

thx

**Closed** 2018-05-11 09:35 UTC

**Comment by plebreton** [comment] 2018-05-11 09:37
_-_2-&211-&


---- Tobias Hermann wrote ----


Closed #42<https://github.com/Dobiasd/frugally-deep/issues/42>.

**Comment by Dobiasd** [comment] 2018-05-11 09:48
@plebreton What do you mean by the following? ;)
> _-_2-&211-&

**Comment by plebreton** [comment] 2018-05-11 09:52
Sorry.... Stupid phone in the pocket...

**Comment by Dobiasd** [comment] 2018-05-11 09:55
No problem. Just wanted to make sure it wasn't more code for "Help, I'm trapped in a neural network." or something. ;)
